### ISSUE TITLE
Add base swerve drive code to codebase

### ISSUE THREAD

**Issue by gbuckholtz** [Machine-Mavericks/FRC-2022#1]
@gregk27 is going to add the base code for swerve

**Comment by gbuckholtz** [comment]
We tried out this code on the robot on Saturday.  @gregk27 , do you think that it is good enough to merge into master

**Comment by gregk27** [comment]
The core subsystem should be done, but the command hasn't been pushed (I can push it up with the CANIDs in a minute).
I wouldn't consider the code done (still needs calibration and more work on the command), but those can be broken into their own issues.

**Comment by gbuckholtz** [comment]
I would like to work with @OliviaODriscoll to get the command they made on the PC in the lab.  It is configured to behave like they have had it work in the past. 

There are two options.  

1. Check in the swerve code with the command removed, then merge in the new command code
2. Check in the swerve with the command and then remove it after the new command has been merged in.

Neither way is ideal.  6 of one 1/2 dozen of the other, really.  Perhaps, less work to merge your whole multi-swerve in and deal with the merge of the new Command after.    I am leaning that way.

**Comment by gregk27** [comment]
Half a second late lol. Honestly it should be pretty easy to just handle the conflicts in the lab (should only be 3-5 lines tops)

As for the multi-swerve, it doesn't have any command attached yet so once an improved command is tested on the Falcon base it'll be a clean merge to get it on the Neos.
